services:
  dap-mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dap-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
      - MARIADB_PASSWORD=nextcloud
    networks:
      - dap-red
    volumes:
      - dap-mariadb-data:/var/lib/mysql

  dap-adminer:
    image: adminer:latest
    container_name: dap-adminer
    ports:
      - "8090:8080"
    networks:
      - dap-red
    depends_on:
      - dap-mariadb
    
  dap-nextcloud:
    image: nextcloud:stable
    container_name: dap-nextcloud
    networks:
      - dap-red
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=dap-mariadb
    ports:
      - "8085:80"
    depends_on:
      - dap-mariadb

networks:
  dap-red:
    driver: bridge
volumes:
  dap-mariadb-data:
    driver: local